# training-service
server:
  port: 8082

spring:
  application:
    name: training-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.102:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.102:3306/campus_training?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

knife4j:
  enable: true

springdoc:
  packages-to-scan: com.campustrain.trainingservice.controller
  paths-to-match: /trainings/**,/courses/**,/chapters/**,/lessons/**
